name: reusable workflow

on:
  workflow_call:
    inputs:
      environment-name:
        required: true
        type: string
    outputs:
      foundenvironment:
        description: "The environment that was found"
        value: ${{ jobs.does_work.outputs.output_env }}

jobs:
  does_work:
    runs-on: ubuntu-latest
    outputs:
      output_env: ${{ steps.step2.outputs.foundenvironment }}
    steps:
    - id: step2
      run: |
        echo "Seeing $ENV_GRABBED, passing it to output"
        echo "foundenvironment=$ENV_GRABBED" >> $GITHUB_OUTPUT
      env: 
        ENV_GRABBED: ${{ inputs.environment-name }}