name: main workflow
run-name: It appears @${{ github.actor }} started a workflow
on:
  # push:
  #   tags:
  #     - *.-release
  workflow_dispatch

jobs:
  try-using-nested-workflow:
    # uses: vduits/actions-test/.github/workflows/fakeauthflow.yaml@main
    uses: ./.github/workflows/fakeauthflow.yaml
    with:
      environment-name: development
  reveal-output:
    runs-on: ubuntu-latest
    needs: try-using-nested-workflow
    steps:
      - run: echo Hello ${{ needs.try-using-nested-workflow.outputs.foundenvironment }}